// Code generated by golden-configgen. DO NOT EDIT.
// Source: spec.yaml

//! Structured logging generated from spec.yaml.
//!
//! One sorted JSON object per line. Keys are sorted so two languages produce
//! byte identical lines.

#![allow(dead_code)]

use std::collections::BTreeMap;

/// A log severity.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum Level {
    Debug,
    Info,
    Warn,
    Error,
}

impl Level {
    /// Map a level name to a Level. Unknown names fall back to info.
    pub fn parse(s: &str) -> Self {
        match s.trim().to_ascii_lowercase().as_str() {
            "debug" => Level::Debug,
            "warn" | "warning" => Level::Warn,
            "error" => Level::Error,
            _ => Level::Info,
        }
    }

    /// Render as it appears on the wire.
    pub fn as_str(self) -> &'static str {
        match self {
            Level::Debug => "debug",
            Level::Info => "info",
            Level::Warn => "warn",
            Level::Error => "error",
        }
    }
}

/// A field value the logger can render.
#[derive(Debug, Clone)]
pub enum Value {
    Str(String),
    Int(i64),
    Bool(bool),
}

impl Value {
    fn render(&self) -> String {
        match self {
            Value::Str(s) => format!("\"{}\"", escape(s)),
            Value::Int(i) => i.to_string(),
            Value::Bool(b) => b.to_string(),
        }
    }
}

fn escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\t' => out.push_str("\\t"),
            '\r' => out.push_str("\\r"),
            c => out.push(c),
        }
    }

    out
}

/// Writes one sorted JSON object per line.
pub struct Logger {
    level: Level,
    service: String,
}

impl Logger {
    /// Build a logger for a service at a level.
    pub fn new(level: &str, service: &str) -> Self {
        Self {
            level: Level::parse(level),
            service: service.to_string(),
        }
    }

    pub fn debug(&self, msg: &str, fields: &[(&str, Value)]) {
        self.log(Level::Debug, msg, fields);
    }

    pub fn info(&self, msg: &str, fields: &[(&str, Value)]) {
        self.log(Level::Info, msg, fields);
    }

    pub fn warn(&self, msg: &str, fields: &[(&str, Value)]) {
        self.log(Level::Warn, msg, fields);
    }

    pub fn error(&self, msg: &str, fields: &[(&str, Value)]) {
        self.log(Level::Error, msg, fields);
    }

    fn log(&self, level: Level, msg: &str, fields: &[(&str, Value)]) {
        if level < self.level {
            return;
        }

        // BTreeMap keeps keys sorted, which is the cross language contract.
        let mut merged: BTreeMap<String, Value> = BTreeMap::new();
        merged.insert("level".to_string(), Value::Str(level.as_str().to_string()));
        merged.insert("msg".to_string(), Value::Str(msg.to_string()));
        merged.insert("service".to_string(), Value::Str(self.service.clone()));
        for (k, v) in fields {
            merged.insert((*k).to_string(), v.clone());
        }

        let pairs: Vec<String> = merged
            .iter()
            .map(|(k, v)| format!("\"{}\":{}", escape(k), v.render()))
            .collect();

        let mut line = String::from("{");
        line.push_str(&pairs.join(","));
        line.push('}');

        eprintln!("{line}");
    }
}
