// Code generated by golden-configgen. DO NOT EDIT.
// Source: spec.yaml

//! Metrics and W3C trace context generated from spec.yaml.

#![allow(dead_code)]

use std::collections::BTreeMap;

pub const BUCKETS: [f64; 11] = [0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0];

/// Render a float the one agreed way. No exponent. No trailing zeros.
pub fn format_float(f: f64) -> String {
    if f == f.trunc() && f.abs() < 1e16 {
        return format!("{}", f as i64);
    }

    let mut s = format!("{f}");
    if s.contains('e') || s.contains('E') {
        s = format!("{f:.17}");
    }
    if s.contains('.') {
        s = s.trim_end_matches('0').trim_end_matches('.').to_string();
    }

    s
}

/// Join a metric name and a label set.
///
/// Built by hand rather than with format!. Braces in a format string collide
/// with the Go template that generates this file.
fn braced(base: &str, inner: &str) -> String {
    let mut out = String::with_capacity(base.len() + inner.len() + 2);
    out.push_str(base);
    out.push('{');
    out.push_str(inner);
    out.push('}');

    out
}

fn key_of(name: &str, labels: &[(&str, &str)]) -> String {
    if labels.is_empty() {
        return name.to_string();
    }

    let sorted: BTreeMap<&str, &str> = labels.iter().copied().collect();
    let parts: Vec<String> = sorted.iter().map(|(k, v)| format!("{k}=\"{v}\"")).collect();

    braced(name, &parts.join(","))
}

fn base_name(k: &str) -> String {
    match k.find('{') {
        Some(i) => k[..i].to_string(),
        None => k.to_string(),
    }
}

fn with_label(k: &str, label: &str, value: &str) -> String {
    let base = base_name(k);
    let inner = match k.find('{') {
        Some(i) => k[i + 1..k.len() - 1].to_string(),
        None => String::new(),
    };
    let pair = format!("{label}=\"{value}\"");

    if inner.is_empty() {
        return braced(&base, &pair);
    }

    let mut parts: Vec<String> = inner.split(',').map(str::to_string).collect();
    parts.push(pair);
    parts.sort();

    braced(&base, &parts.join(","))
}

/// Holds counters and histograms.
#[derive(Default)]
pub struct Registry {
    counters: BTreeMap<String, f64>,
    histograms: BTreeMap<String, Vec<f64>>,
    help: BTreeMap<String, String>,
}

impl Registry {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn inc(&mut self, name: &str, labels: &[(&str, &str)], by: f64, help: &str) {
        *self.counters.entry(key_of(name, labels)).or_insert(0.0) += by;
        self.help.insert(name.to_string(), help.to_string());
    }

    pub fn observe(&mut self, name: &str, labels: &[(&str, &str)], v: f64, help: &str) {
        self.histograms.entry(key_of(name, labels)).or_default().push(v);
        self.help.insert(name.to_string(), help.to_string());
    }

    /// Produce the Prometheus text exposition format.
    pub fn render(&self) -> String {
        let mut out: Vec<String> = Vec::new();
        let mut seen: Vec<String> = Vec::new();

        for (k, v) in &self.counters {
            let base = base_name(k);
            if !seen.contains(&base) {
                let help = self.help.get(&base).cloned().unwrap_or_default();
                out.push(format!("# HELP {base} {help}"));
                out.push(format!("# TYPE {base} counter"));
                seen.push(base.clone());
            }
            out.push(format!("{} {}", k, format_float(*v)));
        }

        for (k, samples) in &self.histograms {
            let base = base_name(k);
            if !seen.contains(&base) {
                let help = self.help.get(&base).cloned().unwrap_or_default();
                out.push(format!("# HELP {base} {help}"));
                out.push(format!("# TYPE {base} histogram"));
                seen.push(base.clone());
            }

            for bound in BUCKETS {
                let count = samples.iter().filter(|s| **s <= bound).count();
                out.push(format!("{} {}", with_label(k, "le", &format_float(bound)), count));
            }
            out.push(format!("{} {}", with_label(k, "le", "+Inf"), samples.len()));
            let sum: f64 = samples.iter().sum();
            out.push(format!("{}_sum {}", base, format_float(sum)));
            out.push(format!("{}_count {}", base, samples.len()));
        }

        if out.is_empty() {
            return String::new();
        }

        let mut s = out.join("\n");
        s.push('\n');

        s
    }
}

/// A parsed W3C traceparent header.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TraceParent {
    pub trace_id: String,
    pub span_id: String,
    pub flags: String,
}

impl TraceParent {
    /// Render the traceparent header value.
    pub fn header(&self) -> String {
        format!("00-{}-{}-{}", self.trace_id, self.span_id, self.flags)
    }

    /// Keep the trace id and start a new span id.
    pub fn child(&self) -> Self {
        Self {
            trace_id: self.trace_id.clone(),
            span_id: rand_hex(8),
            flags: self.flags.clone(),
        }
    }
}

/// Start a brand new trace.
pub fn new_trace() -> TraceParent {
    TraceParent {
        trace_id: rand_hex(16),
        span_id: rand_hex(8),
        flags: "01".to_string(),
    }
}

/// Read a traceparent header. Returns None when unparseable.
pub fn parse_trace_parent(s: &str) -> Option<TraceParent> {
    let parts: Vec<&str> = s.trim().split('-').collect();
    if parts.len() != 4 || parts[0] != "00" {
        return None;
    }
    if parts[1].len() != 32 || parts[2].len() != 16 || parts[3].len() != 2 {
        return None;
    }
    if !parts[1..].iter().all(|p| p.chars().all(|c| c.is_ascii_hexdigit() && !c.is_ascii_uppercase())) {
        return None;
    }
    if parts[1].trim_matches('0').is_empty() || parts[2].trim_matches('0').is_empty() {
        return None;
    }

    Some(TraceParent {
        trace_id: parts[1].to_string(),
        span_id: parts[2].to_string(),
        flags: parts[3].to_string(),
    })
}

/// Random hex without pulling in a random crate.
fn rand_hex(n: usize) -> String {
    use std::time::{SystemTime, UNIX_EPOCH};

    let mut seed = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_nanos() as u64)
        .unwrap_or(0x9E3779B97F4A7C15);

    let mut out = String::with_capacity(n * 2);
    for _ in 0..n {
        // xorshift64. Good enough for a span id and it adds no dependency.
        seed ^= seed << 13;
        seed ^= seed >> 7;
        seed ^= seed << 17;
        out.push_str(&format!("{:02x}", (seed & 0xff) as u8));
    }

    out
}
