// Code generated by golden-configgen. DO NOT EDIT.
// Source: spec.yaml

//! Config loaders generated from spec.yaml.
//!
//! Precedence is flag then env then default. Durations are integer milliseconds.

#![allow(dead_code)]

use std::collections::HashMap;
use std::env;

/// Errors config loading can produce.
#[derive(Debug)]
pub enum ConfigError {
    MissingRequired(String),
    UnknownFlag(String),
    Parse(String),
}

impl std::fmt::Display for ConfigError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ConfigError::MissingRequired(k) => write!(f, "resolving {k}"),
            ConfigError::UnknownFlag(k) => write!(f, "checking flag {k:?}"),
            ConfigError::Parse(m) => write!(f, "{m}"),
        }
    }
}

impl std::error::Error for ConfigError {}

/// Parse a Go style duration into whole milliseconds.
fn parse_duration_ms(raw: &str) -> Result<i64, ConfigError> {
    let raw = raw.trim();
    let split = raw
        .find(|c: char| c.is_alphabetic())
        .ok_or_else(|| ConfigError::Parse(format!("parsing duration {raw:?}")))?;

    let (num, unit) = raw.split_at(split);
    let value: f64 = num
        .parse()
        .map_err(|_| ConfigError::Parse(format!("parsing duration {raw:?}")))?;

    let ms = match unit {
        "ns" => value / 1_000_000.0,
        "us" => value / 1_000.0,
        "ms" => value,
        "s" => value * 1_000.0,
        "m" => value * 60_000.0,
        "h" => value * 3_600_000.0,
        _ => return Err(ConfigError::Parse(format!("parsing duration {raw:?}"))),
    };

    Ok(ms as i64)
}

/// Accept the same spellings as Go strconv::ParseBool.
fn parse_bool(raw: &str) -> Result<bool, ConfigError> {
    match raw.trim().to_ascii_lowercase().as_str() {
        "1" | "t" | "true" => Ok(true),
        "0" | "f" | "false" => Ok(false),
        _ => Err(ConfigError::Parse(format!("parsing bool {raw:?}"))),
    }
}

/// Read --key=value and --key value and bare --flag for bools.
fn parse_flags(
    args: &[String],
    known: &HashMap<&str, bool>,
) -> Result<HashMap<String, String>, ConfigError> {
    let mut out = HashMap::new();
    let mut i = 0;

    while i < args.len() {
        let arg = &args[i];
        if !arg.starts_with("--") {
            i += 1;
            continue;
        }

        let body = &arg[2..];
        let (name, value) = match body.split_once('=') {
            Some((n, v)) => (n.to_string(), Some(v.to_string())),
            None => (body.to_string(), None),
        };

        let is_bool = match known.get(name.as_str()) {
            Some(b) => *b,
            None => return Err(ConfigError::UnknownFlag(name)),
        };

        match value {
            Some(v) => {
                out.insert(name, v);
            }
            None if is_bool => {
                out.insert(name, "true".to_string());
            }
            None if i + 1 < args.len() => {
                i += 1;
                out.insert(name, args[i].clone());
            }
            None => {
                return Err(ConfigError::Parse(format!(
                    "reading flag {name:?}: missing value"
                )))
            }
        }

        i += 1;
    }

    Ok(out)
}

/// Escape a string for the canonical JSON dump.
fn json_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\t' => out.push_str("\\t"),
            '\r' => out.push_str("\\r"),
            c => out.push(c),
        }
    }

    out
}

/// Config for poe-wayfinder.
#[derive(Debug, Clone, PartialEq)]
pub struct PoeWayfinderConfig {
    /// Master switch for all outbound traffic. False makes every request fail before a socket opens. Use it to run the parser offline.
    pub network_enabled: bool,
    /// Refuse any request whose host is not in allowed_hosts. The reference hardcodes an allowlist in main/src/proxy.ts. This makes it config.
    pub block_unlisted_hosts: bool,
    /// Comma separated hosts the app may reach. Default is one host. The reference also ships regional domains and a private server at api.exiledexchange2.dev. We ship neither.
    pub allowed_hosts: String,
    /// Base URL for the official trade API. Every trade path is built from this. English realm only.
    pub trade_base_url: String,
    /// The User-Agent header sent on every request. GGG answers 403 to a request that carries none. Their API policy asks for a descriptive one with contact details. Empty uses a default naming the tool and its version.
    pub user_agent: String,
    /// Padding added to every rate limit window. GGG bans for violations, so the limiter assumes the server clock runs ahead of ours by this much. Raise it if you see 429 responses.
    pub api_latency_seconds: i64,
    /// The POESESSID cookie. Needed for search and fetch. Never log it and never write it to disk in plain text.
    pub poesessid: String,
    /// Which league to search. The trade site keeps a separate index per league, so a wrong one prices an item against a market it is not in. Empty means the current league, read from the trade site's own league list on startup. Naming one here pins it and stops the detection.
    pub league: String,
    /// poe1, poe2, or auto to read it from the open game window. auto keeps reading it, so alt tabbing between the two games moves the parser, the trade endpoint and the window the overlay attaches to.
    pub game: String,
    /// Exact title of the game window the overlay attaches to. Empty derives it from the game, which is what auto detection needs. A title given here pins the window and stops the overlay following the other game.
    pub window_title: String,
    /// Path to Client.txt. The app tails it to learn the current league and character. Empty disables the watcher.
    pub client_log_path: String,
    /// Directory holding items.ndjson and stats.ndjson. Empty uses the refreshed cache in config_dir, and failing that the copy built into this binary. A directory named here always wins, and a bad one is a startup failure rather than a silent fallback.
    pub data_dir: String,
    /// Where user settings, the overlay layout and the refreshed data cache are stored. Empty picks the per user config directory for the platform. A double clicked exe starts in an unpredictable working directory, so a relative default would scatter settings files.
    pub config_dir: String,
    /// Key that triggers a price check on the item under the cursor. The panel closes again when the pointer moves away.
    pub price_check_hotkey: String,
    /// Same check, but the panel stays open and takes focus so it can be read and adjusted. Only Escape, a click outside or Dismiss closes it. This is what Awakened PoE Trade and Exiled Exchange 2 both bind. Empty turns it off.
    pub price_check_locked_hotkey: String,
    /// Chat lines bound to keys, as key=text separated by semicolons. The line is typed and sent. End it with a literal backslash n to type it and leave it for you to finish. An entry with no key is ignored, so a line can be kept here without a binding.
    pub chat_commands: String,
    /// Keys that open the item under the cursor on a reference site, as key=site separated by semicolons. The sites are wiki, poedb and craft of exile. These open your browser rather than being fetched by this app, so the network allowlist does not apply. Empty binds none.
    pub item_link_hotkeys: String,
    /// Stash search presets bound to keys, as key=text separated by semicolons, for example "Ctrl+F1=chaos;Ctrl+F2=exalted". Pressing one opens the stash search box and types the text. Empty binds nothing.
    pub stash_searches: String,
    /// Grabs the panel that is already on screen so it can be clicked without moving the mouse to it, and releases it again. Does nothing when no panel is up. Empty turns it off.
    pub overlay_hotkey: String,
    /// A second binding for the locked check, easier to reach one handed. Empty turns it off.
    pub price_check_locked_alt_hotkey: String,
    /// Controller buttons that fire the locked price check, joined by plus, for example "LB+RB+Y" or "L1+R1+Triangle". Write it in whichever names are printed on your pad. Xbox names are LB, RB, LT, RT, L3, R3, BACK, START, UP, DOWN, LEFT, RIGHT, A, B, X and Y. PlayStation names are L1, R1, L2, R2, L3, R3, CREATE, SHARE, OPTIONS, UP, DOWN, LEFT, RIGHT, CROSS, CIRCLE, SQUARE and TRIANGLE. The two sets name the same buttons, so LB and L1 are one chord. Holding it again closes the panel and hands the game back the foreground, so a pad alone is enough. Empty turns it off. Windows offers no way to hide a pad button from the game, so the game acts on every button in the chord as well. Pick buttons the game does nothing with. Xbox pads are read through XInput and a DualSense or a DualShock 4 is read as a plain HID gamepad, so neither needs extra software. Steam Input takes a pad for itself, so a pad it has claimed is read through the virtual Xbox pad it publishes rather than directly.
    pub gamepad_chord: String,
    /// A file of pad presses to play instead of reading a real controller. Windows offers no way to synthesise a gamepad press, so this is the only way a harness can drive the pad path. Each line is "wait N", "press BUTTONS" or "hold BUTTONS N", counted in polls of the frame loop rather than in seconds, so a run is the same on a fast machine and a slow one. Empty means read the real pads, which is what a player wants.
    pub gamepad_script: String,
    /// Put the old clipboard back after reading the item. The app must copy to read the item, which destroys whatever the user had.
    pub restore_clipboard: bool,
    /// One of debug, info, warn, error.
    pub log_level: String,
}

impl PoeWayfinderConfig {
    /// Resolve config from flags then env then defaults.
    pub fn load(args: &[String]) -> Result<Self, ConfigError> {
        let mut known: HashMap<&str, bool> = HashMap::new();
        known.insert("network-enabled", true);
        known.insert("block-unlisted-hosts", true);
        known.insert("allowed-hosts", false);
        known.insert("trade-base-url", false);
        known.insert("user-agent", false);
        known.insert("api-latency-seconds", false);
        known.insert("poesessid", false);
        known.insert("league", false);
        known.insert("game", false);
        known.insert("window-title", false);
        known.insert("client-log-path", false);
        known.insert("data-dir", false);
        known.insert("config-dir", false);
        known.insert("price-check-hotkey", false);
        known.insert("price-check-locked-hotkey", false);
        known.insert("chat-commands", false);
        known.insert("item-link-hotkeys", false);
        known.insert("stash-searches", false);
        known.insert("overlay-hotkey", false);
        known.insert("price-check-locked-alt-hotkey", false);
        known.insert("gamepad-chord", false);
        known.insert("gamepad-script", false);
        known.insert("restore-clipboard", true);
        known.insert("log-level", false);

        let flags = parse_flags(args, &known)?;

        let raw_network_enabled: Option<String> = None
            .or_else(|| flags.get("network-enabled").cloned())
            .or_else(|| env::var("POE_NETWORK_ENABLED").ok());
        let raw_network_enabled = match raw_network_enabled {
            Some(v) => v,
            None => "true".to_string(),
        };
        let raw_block_unlisted_hosts: Option<String> = None
            .or_else(|| flags.get("block-unlisted-hosts").cloned())
            .or_else(|| env::var("POE_BLOCK_UNLISTED_HOSTS").ok());
        let raw_block_unlisted_hosts = match raw_block_unlisted_hosts {
            Some(v) => v,
            None => "true".to_string(),
        };
        let raw_allowed_hosts: Option<String> = None
            .or_else(|| flags.get("allowed-hosts").cloned())
            .or_else(|| env::var("POE_ALLOWED_HOSTS").ok());
        let raw_allowed_hosts = match raw_allowed_hosts {
            Some(v) => v,
            None => "www.pathofexile.com".to_string(),
        };
        let raw_trade_base_url: Option<String> = None
            .or_else(|| flags.get("trade-base-url").cloned())
            .or_else(|| env::var("POE_TRADE_BASE_URL").ok());
        let raw_trade_base_url = match raw_trade_base_url {
            Some(v) => v,
            None => "https://www.pathofexile.com".to_string(),
        };
        let raw_user_agent: Option<String> = None
            .or_else(|| flags.get("user-agent").cloned())
            .or_else(|| env::var("POE_USER_AGENT").ok());
        let raw_user_agent = match raw_user_agent {
            Some(v) => v,
            None => "".to_string(),
        };
        let raw_api_latency_seconds: Option<String> = None
            .or_else(|| flags.get("api-latency-seconds").cloned())
            .or_else(|| env::var("POE_API_LATENCY_SECONDS").ok());
        let raw_api_latency_seconds = match raw_api_latency_seconds {
            Some(v) => v,
            None => "2".to_string(),
        };
        let raw_poesessid: Option<String> = None
            .or_else(|| flags.get("poesessid").cloned())
            .or_else(|| env::var("POE_SESSION_ID").ok());
        let raw_poesessid = match raw_poesessid {
            Some(v) => v,
            None => "".to_string(),
        };
        let raw_league: Option<String> = None
            .or_else(|| flags.get("league").cloned())
            .or_else(|| env::var("POE_LEAGUE").ok());
        let raw_league = match raw_league {
            Some(v) => v,
            None => "".to_string(),
        };
        let raw_game: Option<String> = None
            .or_else(|| flags.get("game").cloned())
            .or_else(|| env::var("POE_GAME").ok());
        let raw_game = match raw_game {
            Some(v) => v,
            None => "auto".to_string(),
        };
        let raw_window_title: Option<String> = None
            .or_else(|| flags.get("window-title").cloned())
            .or_else(|| env::var("POE_WINDOW_TITLE").ok());
        let raw_window_title = match raw_window_title {
            Some(v) => v,
            None => "".to_string(),
        };
        let raw_client_log_path: Option<String> = None
            .or_else(|| flags.get("client-log-path").cloned())
            .or_else(|| env::var("POE_CLIENT_LOG_PATH").ok());
        let raw_client_log_path = match raw_client_log_path {
            Some(v) => v,
            None => "".to_string(),
        };
        let raw_data_dir: Option<String> = None
            .or_else(|| flags.get("data-dir").cloned())
            .or_else(|| env::var("POE_DATA_DIR").ok());
        let raw_data_dir = match raw_data_dir {
            Some(v) => v,
            None => "".to_string(),
        };
        let raw_config_dir: Option<String> = None
            .or_else(|| flags.get("config-dir").cloned())
            .or_else(|| env::var("POE_CONFIG_DIR").ok());
        let raw_config_dir = match raw_config_dir {
            Some(v) => v,
            None => "".to_string(),
        };
        let raw_price_check_hotkey: Option<String> = None
            .or_else(|| flags.get("price-check-hotkey").cloned())
            .or_else(|| env::var("POE_PRICE_CHECK_HOTKEY").ok());
        let raw_price_check_hotkey = match raw_price_check_hotkey {
            Some(v) => v,
            None => "Ctrl+D".to_string(),
        };
        let raw_price_check_locked_hotkey: Option<String> = None
            .or_else(|| flags.get("price-check-locked-hotkey").cloned())
            .or_else(|| env::var("POE_PRICE_CHECK_LOCKED_HOTKEY").ok());
        let raw_price_check_locked_hotkey = match raw_price_check_locked_hotkey {
            Some(v) => v,
            None => "Ctrl+Alt+D".to_string(),
        };
        let raw_chat_commands: Option<String> = None
            .or_else(|| flags.get("chat-commands").cloned())
            .or_else(|| env::var("POE_CHAT_COMMANDS").ok());
        let raw_chat_commands = match raw_chat_commands {
            Some(v) => v,
            None => "F5=/hideout;F9=/exit".to_string(),
        };
        let raw_item_link_hotkeys: Option<String> = None
            .or_else(|| flags.get("item-link-hotkeys").cloned())
            .or_else(|| env::var("POE_ITEM_LINK_HOTKEYS").ok());
        let raw_item_link_hotkeys = match raw_item_link_hotkeys {
            Some(v) => v,
            None => "Alt+W=wiki;Alt+B=poedb;Alt+C=craft of exile".to_string(),
        };
        let raw_stash_searches: Option<String> = None
            .or_else(|| flags.get("stash-searches").cloned())
            .or_else(|| env::var("POE_STASH_SEARCHES").ok());
        let raw_stash_searches = match raw_stash_searches {
            Some(v) => v,
            None => "".to_string(),
        };
        let raw_overlay_hotkey: Option<String> = None
            .or_else(|| flags.get("overlay-hotkey").cloned())
            .or_else(|| env::var("POE_OVERLAY_HOTKEY").ok());
        let raw_overlay_hotkey = match raw_overlay_hotkey {
            Some(v) => v,
            None => "Shift+Space".to_string(),
        };
        let raw_price_check_locked_alt_hotkey: Option<String> = None
            .or_else(|| flags.get("price-check-locked-alt-hotkey").cloned())
            .or_else(|| env::var("POE_PRICE_CHECK_LOCKED_ALT_HOTKEY").ok());
        let raw_price_check_locked_alt_hotkey = match raw_price_check_locked_alt_hotkey {
            Some(v) => v,
            None => "Ctrl+Shift+D".to_string(),
        };
        let raw_gamepad_chord: Option<String> = None
            .or_else(|| flags.get("gamepad-chord").cloned())
            .or_else(|| env::var("POE_GAMEPAD_CHORD").ok());
        let raw_gamepad_chord = match raw_gamepad_chord {
            Some(v) => v,
            None => "L1+R1+Triangle".to_string(),
        };
        let raw_gamepad_script: Option<String> = None
            .or_else(|| flags.get("gamepad-script").cloned())
            .or_else(|| env::var("POE_GAMEPAD_SCRIPT").ok());
        let raw_gamepad_script = match raw_gamepad_script {
            Some(v) => v,
            None => "".to_string(),
        };
        let raw_restore_clipboard: Option<String> = None
            .or_else(|| flags.get("restore-clipboard").cloned())
            .or_else(|| env::var("POE_RESTORE_CLIPBOARD").ok());
        let raw_restore_clipboard = match raw_restore_clipboard {
            Some(v) => v,
            None => "true".to_string(),
        };
        let raw_log_level: Option<String> = None
            .or_else(|| flags.get("log-level").cloned())
            .or_else(|| env::var("POE_LOG_LEVEL").ok());
        let raw_log_level = match raw_log_level {
            Some(v) => v,
            None => "info".to_string(),
        };

        Ok(Self {
            network_enabled: parse_bool(&raw_network_enabled)?,
            block_unlisted_hosts: parse_bool(&raw_block_unlisted_hosts)?,
            allowed_hosts: raw_allowed_hosts,
            trade_base_url: raw_trade_base_url,
            user_agent: raw_user_agent,
            api_latency_seconds: raw_api_latency_seconds.trim().parse().map_err(|_| {
                ConfigError::Parse(format!(
                    "parsing api_latency_seconds {:?} as int",
                    raw_api_latency_seconds
                ))
            })?,
            poesessid: raw_poesessid,
            league: raw_league,
            game: raw_game,
            window_title: raw_window_title,
            client_log_path: raw_client_log_path,
            data_dir: raw_data_dir,
            config_dir: raw_config_dir,
            price_check_hotkey: raw_price_check_hotkey,
            price_check_locked_hotkey: raw_price_check_locked_hotkey,
            chat_commands: raw_chat_commands,
            item_link_hotkeys: raw_item_link_hotkeys,
            stash_searches: raw_stash_searches,
            overlay_hotkey: raw_overlay_hotkey,
            price_check_locked_alt_hotkey: raw_price_check_locked_alt_hotkey,
            gamepad_chord: raw_gamepad_chord,
            gamepad_script: raw_gamepad_script,
            restore_clipboard: parse_bool(&raw_restore_clipboard)?,
            log_level: raw_log_level,
        })
    }

    /// Render the resolved config in the canonical cross language form.
    pub fn json(&self) -> String {
        let mut pairs: Vec<String> = Vec::new();
        pairs.push(format!(
            "{}:{}",
            "\"network_enabled\"", self.network_enabled
        ));
        pairs.push(format!(
            "{}:{}",
            "\"block_unlisted_hosts\"", self.block_unlisted_hosts
        ));
        pairs.push(format!(
            "{}:\"{}\"",
            "\"allowed_hosts\"",
            json_escape(&self.allowed_hosts)
        ));
        pairs.push(format!(
            "{}:\"{}\"",
            "\"trade_base_url\"",
            json_escape(&self.trade_base_url)
        ));
        pairs.push(format!(
            "{}:\"{}\"",
            "\"user_agent\"",
            json_escape(&self.user_agent)
        ));
        pairs.push(format!(
            "{}:{}",
            "\"api_latency_seconds\"", self.api_latency_seconds
        ));
        pairs.push(format!(
            "{}:\"{}\"",
            "\"poesessid\"",
            json_escape(&self.poesessid)
        ));
        pairs.push(format!(
            "{}:\"{}\"",
            "\"league\"",
            json_escape(&self.league)
        ));
        pairs.push(format!("{}:\"{}\"", "\"game\"", json_escape(&self.game)));
        pairs.push(format!(
            "{}:\"{}\"",
            "\"window_title\"",
            json_escape(&self.window_title)
        ));
        pairs.push(format!(
            "{}:\"{}\"",
            "\"client_log_path\"",
            json_escape(&self.client_log_path)
        ));
        pairs.push(format!(
            "{}:\"{}\"",
            "\"data_dir\"",
            json_escape(&self.data_dir)
        ));
        pairs.push(format!(
            "{}:\"{}\"",
            "\"config_dir\"",
            json_escape(&self.config_dir)
        ));
        pairs.push(format!(
            "{}:\"{}\"",
            "\"price_check_hotkey\"",
            json_escape(&self.price_check_hotkey)
        ));
        pairs.push(format!(
            "{}:\"{}\"",
            "\"price_check_locked_hotkey\"",
            json_escape(&self.price_check_locked_hotkey)
        ));
        pairs.push(format!(
            "{}:\"{}\"",
            "\"chat_commands\"",
            json_escape(&self.chat_commands)
        ));
        pairs.push(format!(
            "{}:\"{}\"",
            "\"item_link_hotkeys\"",
            json_escape(&self.item_link_hotkeys)
        ));
        pairs.push(format!(
            "{}:\"{}\"",
            "\"stash_searches\"",
            json_escape(&self.stash_searches)
        ));
        pairs.push(format!(
            "{}:\"{}\"",
            "\"overlay_hotkey\"",
            json_escape(&self.overlay_hotkey)
        ));
        pairs.push(format!(
            "{}:\"{}\"",
            "\"price_check_locked_alt_hotkey\"",
            json_escape(&self.price_check_locked_alt_hotkey)
        ));
        pairs.push(format!(
            "{}:\"{}\"",
            "\"gamepad_chord\"",
            json_escape(&self.gamepad_chord)
        ));
        pairs.push(format!(
            "{}:\"{}\"",
            "\"gamepad_script\"",
            json_escape(&self.gamepad_script)
        ));
        pairs.push(format!(
            "{}:{}",
            "\"restore_clipboard\"", self.restore_clipboard
        ));
        pairs.push(format!(
            "{}:\"{}\"",
            "\"log_level\"",
            json_escape(&self.log_level)
        ));
        pairs.sort();

        // Built by hand rather than with format! so the generator never has to
        // escape braces through a Go template.
        let mut out = String::from("{");
        out.push_str(&pairs.join(","));
        out.push('}');

        out
    }
}

/// Config for poe-wayfinder-cli.
#[derive(Debug, Clone, PartialEq)]
pub struct PoeWayfinderCliConfig {
    /// Master switch for all outbound traffic.
    pub network_enabled: bool,
    /// Refuse any request whose host is not in allowed_hosts.
    pub block_unlisted_hosts: bool,
    /// Comma separated hosts the app may reach.
    pub allowed_hosts: String,
    /// Base URL for the official trade API.
    pub trade_base_url: String,
    /// The User-Agent header sent on every request. GGG answers 403 to a request that carries none. Their API policy asks for a descriptive one with contact details. Empty uses a default naming the tool and its version.
    pub user_agent: String,
    /// Padding added to every rate limit window.
    pub api_latency_seconds: i64,
    /// The POESESSID cookie.
    pub poesessid: String,
    /// Which league to search. The trade site keeps a separate index per league, so a wrong one prices an item against a market it is not in. Empty means the current league, read from the trade site's own league list on startup. Naming one here pins it and stops the detection.
    pub league: String,
    /// Which game to parse for. Either poe1 or poe2.
    pub game: String,
    /// Directory holding items.ndjson and stats.ndjson. Empty uses the refreshed cache in config_dir, and failing that the copy built into this binary. A directory named here always wins, and a bad one is a startup failure rather than a silent fallback.
    pub data_dir: String,
    /// Read item text from this file instead of the clipboard.
    pub item_file: String,
    /// One of debug, info, warn, error.
    pub log_level: String,
}

impl PoeWayfinderCliConfig {
    /// Resolve config from flags then env then defaults.
    pub fn load(args: &[String]) -> Result<Self, ConfigError> {
        let mut known: HashMap<&str, bool> = HashMap::new();
        known.insert("network-enabled", true);
        known.insert("block-unlisted-hosts", true);
        known.insert("allowed-hosts", false);
        known.insert("trade-base-url", false);
        known.insert("user-agent", false);
        known.insert("api-latency-seconds", false);
        known.insert("poesessid", false);
        known.insert("league", false);
        known.insert("game", false);
        known.insert("data-dir", false);
        known.insert("item-file", false);
        known.insert("log-level", false);

        let flags = parse_flags(args, &known)?;

        let raw_network_enabled: Option<String> = None
            .or_else(|| flags.get("network-enabled").cloned())
            .or_else(|| env::var("POE_NETWORK_ENABLED").ok());
        let raw_network_enabled = match raw_network_enabled {
            Some(v) => v,
            None => "true".to_string(),
        };
        let raw_block_unlisted_hosts: Option<String> = None
            .or_else(|| flags.get("block-unlisted-hosts").cloned())
            .or_else(|| env::var("POE_BLOCK_UNLISTED_HOSTS").ok());
        let raw_block_unlisted_hosts = match raw_block_unlisted_hosts {
            Some(v) => v,
            None => "true".to_string(),
        };
        let raw_allowed_hosts: Option<String> = None
            .or_else(|| flags.get("allowed-hosts").cloned())
            .or_else(|| env::var("POE_ALLOWED_HOSTS").ok());
        let raw_allowed_hosts = match raw_allowed_hosts {
            Some(v) => v,
            None => "www.pathofexile.com".to_string(),
        };
        let raw_trade_base_url: Option<String> = None
            .or_else(|| flags.get("trade-base-url").cloned())
            .or_else(|| env::var("POE_TRADE_BASE_URL").ok());
        let raw_trade_base_url = match raw_trade_base_url {
            Some(v) => v,
            None => "https://www.pathofexile.com".to_string(),
        };
        let raw_user_agent: Option<String> = None
            .or_else(|| flags.get("user-agent").cloned())
            .or_else(|| env::var("POE_USER_AGENT").ok());
        let raw_user_agent = match raw_user_agent {
            Some(v) => v,
            None => "".to_string(),
        };
        let raw_api_latency_seconds: Option<String> = None
            .or_else(|| flags.get("api-latency-seconds").cloned())
            .or_else(|| env::var("POE_API_LATENCY_SECONDS").ok());
        let raw_api_latency_seconds = match raw_api_latency_seconds {
            Some(v) => v,
            None => "2".to_string(),
        };
        let raw_poesessid: Option<String> = None
            .or_else(|| flags.get("poesessid").cloned())
            .or_else(|| env::var("POE_SESSION_ID").ok());
        let raw_poesessid = match raw_poesessid {
            Some(v) => v,
            None => "".to_string(),
        };
        let raw_league: Option<String> = None
            .or_else(|| flags.get("league").cloned())
            .or_else(|| env::var("POE_LEAGUE").ok());
        let raw_league = match raw_league {
            Some(v) => v,
            None => "".to_string(),
        };
        let raw_game: Option<String> = None
            .or_else(|| flags.get("game").cloned())
            .or_else(|| env::var("POE_GAME").ok());
        let raw_game = match raw_game {
            Some(v) => v,
            None => "poe2".to_string(),
        };
        let raw_data_dir: Option<String> = None
            .or_else(|| flags.get("data-dir").cloned())
            .or_else(|| env::var("POE_DATA_DIR").ok());
        let raw_data_dir = match raw_data_dir {
            Some(v) => v,
            None => "".to_string(),
        };
        let raw_item_file: Option<String> = None
            .or_else(|| flags.get("item-file").cloned())
            .or_else(|| env::var("POE_ITEM_FILE").ok());
        let raw_item_file = match raw_item_file {
            Some(v) => v,
            None => "".to_string(),
        };
        let raw_log_level: Option<String> = None
            .or_else(|| flags.get("log-level").cloned())
            .or_else(|| env::var("POE_LOG_LEVEL").ok());
        let raw_log_level = match raw_log_level {
            Some(v) => v,
            None => "info".to_string(),
        };

        Ok(Self {
            network_enabled: parse_bool(&raw_network_enabled)?,
            block_unlisted_hosts: parse_bool(&raw_block_unlisted_hosts)?,
            allowed_hosts: raw_allowed_hosts,
            trade_base_url: raw_trade_base_url,
            user_agent: raw_user_agent,
            api_latency_seconds: raw_api_latency_seconds.trim().parse().map_err(|_| {
                ConfigError::Parse(format!(
                    "parsing api_latency_seconds {:?} as int",
                    raw_api_latency_seconds
                ))
            })?,
            poesessid: raw_poesessid,
            league: raw_league,
            game: raw_game,
            data_dir: raw_data_dir,
            item_file: raw_item_file,
            log_level: raw_log_level,
        })
    }

    /// Render the resolved config in the canonical cross language form.
    pub fn json(&self) -> String {
        let mut pairs: Vec<String> = Vec::new();
        pairs.push(format!(
            "{}:{}",
            "\"network_enabled\"", self.network_enabled
        ));
        pairs.push(format!(
            "{}:{}",
            "\"block_unlisted_hosts\"", self.block_unlisted_hosts
        ));
        pairs.push(format!(
            "{}:\"{}\"",
            "\"allowed_hosts\"",
            json_escape(&self.allowed_hosts)
        ));
        pairs.push(format!(
            "{}:\"{}\"",
            "\"trade_base_url\"",
            json_escape(&self.trade_base_url)
        ));
        pairs.push(format!(
            "{}:\"{}\"",
            "\"user_agent\"",
            json_escape(&self.user_agent)
        ));
        pairs.push(format!(
            "{}:{}",
            "\"api_latency_seconds\"", self.api_latency_seconds
        ));
        pairs.push(format!(
            "{}:\"{}\"",
            "\"poesessid\"",
            json_escape(&self.poesessid)
        ));
        pairs.push(format!(
            "{}:\"{}\"",
            "\"league\"",
            json_escape(&self.league)
        ));
        pairs.push(format!("{}:\"{}\"", "\"game\"", json_escape(&self.game)));
        pairs.push(format!(
            "{}:\"{}\"",
            "\"data_dir\"",
            json_escape(&self.data_dir)
        ));
        pairs.push(format!(
            "{}:\"{}\"",
            "\"item_file\"",
            json_escape(&self.item_file)
        ));
        pairs.push(format!(
            "{}:\"{}\"",
            "\"log_level\"",
            json_escape(&self.log_level)
        ));
        pairs.sort();

        // Built by hand rather than with format! so the generator never has to
        // escape braces through a Go template.
        let mut out = String::from("{");
        out.push_str(&pairs.join(","));
        out.push('}');

        out
    }
}

/// Config for poe-wayfinder-datagen.
#[derive(Debug, Clone, PartialEq)]
pub struct PoeWayfinderDatagenConfig {
    /// Master switch for all outbound traffic.
    pub network_enabled: bool,
    /// Refuse any request whose host is not in allowed_hosts.
    pub block_unlisted_hosts: bool,
    /// Comma separated hosts the builder may reach.
    pub allowed_hosts: String,
    /// Base URL used to pull the trade stat and item tables.
    pub trade_base_url: String,
    /// The User-Agent header sent on every request. GGG answers 403 to a request that carries none. Their API policy asks for a descriptive one with contact details. Empty uses a default naming the tool and its version.
    pub user_agent: String,
    /// Padding added to every rate limit window.
    pub api_latency_seconds: i64,
    /// Directory holding the extracted game tables.
    pub tables_dir: String,
    /// Where items.ndjson and stats.ndjson are written.
    pub out_dir: String,
    /// Which game to build data for. Either poe1 or poe2.
    pub game: String,
    /// One of debug, info, warn, error.
    pub log_level: String,
}

impl PoeWayfinderDatagenConfig {
    /// Resolve config from flags then env then defaults.
    pub fn load(args: &[String]) -> Result<Self, ConfigError> {
        let mut known: HashMap<&str, bool> = HashMap::new();
        known.insert("network-enabled", true);
        known.insert("block-unlisted-hosts", true);
        known.insert("allowed-hosts", false);
        known.insert("trade-base-url", false);
        known.insert("user-agent", false);
        known.insert("api-latency-seconds", false);
        known.insert("tables-dir", false);
        known.insert("out-dir", false);
        known.insert("game", false);
        known.insert("log-level", false);

        let flags = parse_flags(args, &known)?;

        let raw_network_enabled: Option<String> = None
            .or_else(|| flags.get("network-enabled").cloned())
            .or_else(|| env::var("POE_NETWORK_ENABLED").ok());
        let raw_network_enabled = match raw_network_enabled {
            Some(v) => v,
            None => "true".to_string(),
        };
        let raw_block_unlisted_hosts: Option<String> = None
            .or_else(|| flags.get("block-unlisted-hosts").cloned())
            .or_else(|| env::var("POE_BLOCK_UNLISTED_HOSTS").ok());
        let raw_block_unlisted_hosts = match raw_block_unlisted_hosts {
            Some(v) => v,
            None => "true".to_string(),
        };
        let raw_allowed_hosts: Option<String> = None
            .or_else(|| flags.get("allowed-hosts").cloned())
            .or_else(|| env::var("POE_ALLOWED_HOSTS").ok());
        let raw_allowed_hosts = match raw_allowed_hosts {
            Some(v) => v,
            None => "www.pathofexile.com".to_string(),
        };
        let raw_trade_base_url: Option<String> = None
            .or_else(|| flags.get("trade-base-url").cloned())
            .or_else(|| env::var("POE_TRADE_BASE_URL").ok());
        let raw_trade_base_url = match raw_trade_base_url {
            Some(v) => v,
            None => "https://www.pathofexile.com".to_string(),
        };
        let raw_user_agent: Option<String> = None
            .or_else(|| flags.get("user-agent").cloned())
            .or_else(|| env::var("POE_USER_AGENT").ok());
        let raw_user_agent = match raw_user_agent {
            Some(v) => v,
            None => "".to_string(),
        };
        let raw_api_latency_seconds: Option<String> = None
            .or_else(|| flags.get("api-latency-seconds").cloned())
            .or_else(|| env::var("POE_API_LATENCY_SECONDS").ok());
        let raw_api_latency_seconds = match raw_api_latency_seconds {
            Some(v) => v,
            None => "2".to_string(),
        };
        let raw_tables_dir: Option<String> = None
            .or_else(|| flags.get("tables-dir").cloned())
            .or_else(|| env::var("POE_TABLES_DIR").ok());
        let raw_tables_dir = match raw_tables_dir {
            Some(v) => v,
            None => return Err(ConfigError::MissingRequired("tables_dir".to_string())),
        };
        let raw_out_dir: Option<String> = None
            .or_else(|| flags.get("out-dir").cloned())
            .or_else(|| env::var("POE_OUT_DIR").ok());
        let raw_out_dir = match raw_out_dir {
            Some(v) => v,
            None => return Err(ConfigError::MissingRequired("out_dir".to_string())),
        };
        let raw_game: Option<String> = None
            .or_else(|| flags.get("game").cloned())
            .or_else(|| env::var("POE_GAME").ok());
        let raw_game = match raw_game {
            Some(v) => v,
            None => "poe2".to_string(),
        };
        let raw_log_level: Option<String> = None
            .or_else(|| flags.get("log-level").cloned())
            .or_else(|| env::var("POE_LOG_LEVEL").ok());
        let raw_log_level = match raw_log_level {
            Some(v) => v,
            None => "info".to_string(),
        };

        Ok(Self {
            network_enabled: parse_bool(&raw_network_enabled)?,
            block_unlisted_hosts: parse_bool(&raw_block_unlisted_hosts)?,
            allowed_hosts: raw_allowed_hosts,
            trade_base_url: raw_trade_base_url,
            user_agent: raw_user_agent,
            api_latency_seconds: raw_api_latency_seconds.trim().parse().map_err(|_| {
                ConfigError::Parse(format!(
                    "parsing api_latency_seconds {:?} as int",
                    raw_api_latency_seconds
                ))
            })?,
            tables_dir: raw_tables_dir,
            out_dir: raw_out_dir,
            game: raw_game,
            log_level: raw_log_level,
        })
    }

    /// Render the resolved config in the canonical cross language form.
    pub fn json(&self) -> String {
        let mut pairs: Vec<String> = Vec::new();
        pairs.push(format!(
            "{}:{}",
            "\"network_enabled\"", self.network_enabled
        ));
        pairs.push(format!(
            "{}:{}",
            "\"block_unlisted_hosts\"", self.block_unlisted_hosts
        ));
        pairs.push(format!(
            "{}:\"{}\"",
            "\"allowed_hosts\"",
            json_escape(&self.allowed_hosts)
        ));
        pairs.push(format!(
            "{}:\"{}\"",
            "\"trade_base_url\"",
            json_escape(&self.trade_base_url)
        ));
        pairs.push(format!(
            "{}:\"{}\"",
            "\"user_agent\"",
            json_escape(&self.user_agent)
        ));
        pairs.push(format!(
            "{}:{}",
            "\"api_latency_seconds\"", self.api_latency_seconds
        ));
        pairs.push(format!(
            "{}:\"{}\"",
            "\"tables_dir\"",
            json_escape(&self.tables_dir)
        ));
        pairs.push(format!(
            "{}:\"{}\"",
            "\"out_dir\"",
            json_escape(&self.out_dir)
        ));
        pairs.push(format!("{}:\"{}\"", "\"game\"", json_escape(&self.game)));
        pairs.push(format!(
            "{}:\"{}\"",
            "\"log_level\"",
            json_escape(&self.log_level)
        ));
        pairs.sort();

        // Built by hand rather than with format! so the generator never has to
        // escape braces through a Go template.
        let mut out = String::from("{");
        out.push_str(&pairs.join(","));
        out.push('}');

        out
    }
}
