// Code generated by golden-configgen. DO NOT EDIT.
// Source: spec.yaml

//! Resilience policy generated from spec.yaml.
//!
//! Timeouts and retries and a circuit breaker. Durations are milliseconds.

#![allow(dead_code)]

/// Resilience policy for a client.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Policy {
    pub timeout_ms: i64,
    pub max_attempts: i64,
    pub backoff_base_ms: i64,
    pub backoff_max_ms: i64,
    pub breaker_failures: i64,
    pub breaker_cooldown_ms: i64,
}

/// Report whether an outcome deserves another attempt.
///
/// status 0 means a transport error which is always retryable.
pub fn retryable(status: i64) -> bool {
    if status == 0 || status == 429 {
        return true;
    }

    status >= 500
}

/// Return the wait in milliseconds before a zero based attempt.
pub fn backoff_for(p: &Policy, attempt: i64) -> i64 {
    if attempt <= 0 {
        return 0;
    }

    let mut d = p.backoff_base_ms;
    let mut i = 1;
    while i < attempt {
        d *= 2;
        if d >= p.backoff_max_ms {
            return p.backoff_max_ms;
        }
        i += 1;
    }

    d.min(p.backoff_max_ms)
}

/// Counts consecutive failures and opens after the threshold.
pub struct Breaker {
    policy: Policy,
    failures: i64,
    opened_at_ms: i64,
}

impl Breaker {
    pub fn new(policy: Policy) -> Self {
        Self {
            policy,
            failures: 0,
            opened_at_ms: 0,
        }
    }

    /// Report whether a call may proceed.
    pub fn allow(&self, now_ms: i64) -> bool {
        if self.failures < self.policy.breaker_failures {
            return true;
        }

        now_ms - self.opened_at_ms >= self.policy.breaker_cooldown_ms
    }

    /// Update the breaker with the outcome of a call.
    pub fn record(&mut self, now_ms: i64, ok: bool) {
        if ok {
            self.failures = 0;
            return;
        }

        self.failures += 1;
        if self.failures == self.policy.breaker_failures {
            self.opened_at_ms = now_ms;
        }
    }

    pub fn failures(&self) -> i64 {
        self.failures
    }
}
